# $Id: Makefile 5207 2010-11-06 06:04:48Z kcwu $

SRCROOT=	../..
.include "$(SRCROOT)/pttbbs.mk"

SRCS:=	cpuload.c proctitle.c strlcat.c strlcpy.c memusage.c
LIB:=	osdep

all: .depend

install:

.include <bsd.lib.mk>
